plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/home/oni/loadline/site/dist"
publishOrigin = "ui"
commandOrigin = "ui"
base = "/home/oni/loadline/site"
command = "npm run build"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]